// 
// Decompiled by Procyon v0.5.36
// 

package net.optifine.config;

public class Option
{
    public static final enq FOG_FANCY;
    public static final enq FOG_START;
    public static final enq MIPMAP_TYPE;
    public static final enq SMOOTH_FPS;
    public static final enq CLOUDS;
    public static final enq CLOUD_HEIGHT;
    public static final enq TREES;
    public static final enq RAIN;
    public static final enq ANIMATED_WATER;
    public static final enq ANIMATED_LAVA;
    public static final enq ANIMATED_FIRE;
    public static final enq ANIMATED_PORTAL;
    public static final enq AO_LEVEL;
    public static final enq LAGOMETER;
    public static final enq SHOW_FPS;
    public static final enq AUTOSAVE_TICKS;
    public static final enq BETTER_GRASS;
    public static final enq ANIMATED_REDSTONE;
    public static final enq ANIMATED_EXPLOSION;
    public static final enq ANIMATED_FLAME;
    public static final enq ANIMATED_SMOKE;
    public static final enq WEATHER;
    public static final enq SKY;
    public static final enq STARS;
    public static final enq SUN_MOON;
    public static final enq VIGNETTE;
    public static final enq CHUNK_UPDATES;
    public static final enq CHUNK_UPDATES_DYNAMIC;
    public static final enq TIME;
    public static final enq SMOOTH_WORLD;
    public static final enq VOID_PARTICLES;
    public static final enq WATER_PARTICLES;
    public static final enq RAIN_SPLASH;
    public static final enq PORTAL_PARTICLES;
    public static final enq POTION_PARTICLES;
    public static final enq FIREWORK_PARTICLES;
    public static final enq PROFILER;
    public static final enq DRIPPING_WATER_LAVA;
    public static final enq BETTER_SNOW;
    public static final enq ANIMATED_TERRAIN;
    public static final enq SWAMP_COLORS;
    public static final enq RANDOM_ENTITIES;
    public static final enq SMOOTH_BIOMES;
    public static final enq CUSTOM_FONTS;
    public static final enq CUSTOM_COLORS;
    public static final enq SHOW_CAPES;
    public static final enq CONNECTED_TEXTURES;
    public static final enq CUSTOM_ITEMS;
    public static final enq AA_LEVEL;
    public static final enq AF_LEVEL;
    public static final enq ANIMATED_TEXTURES;
    public static final enq NATURAL_TEXTURES;
    public static final enq EMISSIVE_TEXTURES;
    public static final enq HELD_ITEM_TOOLTIPS;
    public static final enq LAZY_CHUNK_LOADING;
    public static final enq CUSTOM_SKY;
    public static final enq FAST_MATH;
    public static final enq FAST_RENDER;
    public static final enq DYNAMIC_FOV;
    public static final enq DYNAMIC_LIGHTS;
    public static final enq ALTERNATE_BLOCKS;
    public static final enq CUSTOM_ENTITY_MODELS;
    public static final enq ADVANCED_TOOLTIPS;
    public static final enq SCREENSHOT_SIZE;
    public static final enq CUSTOM_GUIS;
    public static final enq RENDER_REGIONS;
    public static final enq SHOW_GL_ERRORS;
    public static final enq SMART_ANIMATIONS;
    public static final enq CHAT_BACKGROUND;
    public static final enq CHAT_SHADOW;
    public static final enq TELEMETRY;
    
    static {
        Option.FOG_FANCY = new IteratableOptionOF("of.options.FOG_FANCY");
        Option.FOG_START = new IteratableOptionOF("of.options.FOG_START");
        Option.MIPMAP_TYPE = (enq)new SliderPercentageOptionOF("of.options.MIPMAP_TYPE", 0, 3, 1, 3);
        Option.SMOOTH_FPS = new IteratableOptionOF("of.options.SMOOTH_FPS");
        Option.CLOUDS = new IteratableOptionOF("of.options.CLOUDS");
        Option.CLOUD_HEIGHT = (enq)new SliderPercentageOptionOF("of.options.CLOUD_HEIGHT", 0.0);
        Option.TREES = new IteratableOptionOF("of.options.TREES");
        Option.RAIN = new IteratableOptionOF("of.options.RAIN");
        Option.ANIMATED_WATER = new IteratableOptionOF("of.options.ANIMATED_WATER");
        Option.ANIMATED_LAVA = new IteratableOptionOF("of.options.ANIMATED_LAVA");
        Option.ANIMATED_FIRE = new IteratableOptionOF("of.options.ANIMATED_FIRE");
        Option.ANIMATED_PORTAL = new IteratableOptionOF("of.options.ANIMATED_PORTAL");
        Option.AO_LEVEL = (enq)new SliderPercentageOptionOF("of.options.AO_LEVEL", 1.0);
        Option.LAGOMETER = new IteratableOptionOF("of.options.LAGOMETER");
        Option.SHOW_FPS = new IteratableOptionOF("of.options.SHOW_FPS");
        Option.AUTOSAVE_TICKS = new IteratableOptionOF("of.options.AUTOSAVE_TICKS");
        Option.BETTER_GRASS = new IteratableOptionOF("of.options.BETTER_GRASS");
        Option.ANIMATED_REDSTONE = new IteratableOptionOF("of.options.ANIMATED_REDSTONE");
        Option.ANIMATED_EXPLOSION = new IteratableOptionOF("of.options.ANIMATED_EXPLOSION");
        Option.ANIMATED_FLAME = new IteratableOptionOF("of.options.ANIMATED_FLAME");
        Option.ANIMATED_SMOKE = new IteratableOptionOF("of.options.ANIMATED_SMOKE");
        Option.WEATHER = new IteratableOptionOF("of.options.WEATHER");
        Option.SKY = new IteratableOptionOF("of.options.SKY");
        Option.STARS = new IteratableOptionOF("of.options.STARS");
        Option.SUN_MOON = new IteratableOptionOF("of.options.SUN_MOON");
        Option.VIGNETTE = new IteratableOptionOF("of.options.VIGNETTE");
        Option.CHUNK_UPDATES = new IteratableOptionOF("of.options.CHUNK_UPDATES");
        Option.CHUNK_UPDATES_DYNAMIC = new IteratableOptionOF("of.options.CHUNK_UPDATES_DYNAMIC");
        Option.TIME = new IteratableOptionOF("of.options.TIME");
        Option.SMOOTH_WORLD = new IteratableOptionOF("of.options.SMOOTH_WORLD");
        Option.VOID_PARTICLES = new IteratableOptionOF("of.options.VOID_PARTICLES");
        Option.WATER_PARTICLES = new IteratableOptionOF("of.options.WATER_PARTICLES");
        Option.RAIN_SPLASH = new IteratableOptionOF("of.options.RAIN_SPLASH");
        Option.PORTAL_PARTICLES = new IteratableOptionOF("of.options.PORTAL_PARTICLES");
        Option.POTION_PARTICLES = new IteratableOptionOF("of.options.POTION_PARTICLES");
        Option.FIREWORK_PARTICLES = new IteratableOptionOF("of.options.FIREWORK_PARTICLES");
        Option.PROFILER = new IteratableOptionOF("of.options.PROFILER");
        Option.DRIPPING_WATER_LAVA = new IteratableOptionOF("of.options.DRIPPING_WATER_LAVA");
        Option.BETTER_SNOW = new IteratableOptionOF("of.options.BETTER_SNOW");
        Option.ANIMATED_TERRAIN = new IteratableOptionOF("of.options.ANIMATED_TERRAIN");
        Option.SWAMP_COLORS = new IteratableOptionOF("of.options.SWAMP_COLORS");
        Option.RANDOM_ENTITIES = new IteratableOptionOF("of.options.RANDOM_ENTITIES");
        Option.SMOOTH_BIOMES = new IteratableOptionOF("of.options.SMOOTH_BIOMES");
        Option.CUSTOM_FONTS = new IteratableOptionOF("of.options.CUSTOM_FONTS");
        Option.CUSTOM_COLORS = new IteratableOptionOF("of.options.CUSTOM_COLORS");
        Option.SHOW_CAPES = new IteratableOptionOF("of.options.SHOW_CAPES");
        Option.CONNECTED_TEXTURES = new IteratableOptionOF("of.options.CONNECTED_TEXTURES");
        Option.CUSTOM_ITEMS = new IteratableOptionOF("of.options.CUSTOM_ITEMS");
        Option.AA_LEVEL = (enq)new SliderPercentageOptionOF("of.options.AA_LEVEL", 0, 16, new int[] { 0, 2, 4, 6, 8, 12, 16 }, 0);
        Option.AF_LEVEL = (enq)new SliderPercentageOptionOF("of.options.AF_LEVEL", 1, 16, new int[] { 1, 2, 4, 8, 16 }, 1);
        Option.ANIMATED_TEXTURES = new IteratableOptionOF("of.options.ANIMATED_TEXTURES");
        Option.NATURAL_TEXTURES = new IteratableOptionOF("of.options.NATURAL_TEXTURES");
        Option.EMISSIVE_TEXTURES = new IteratableOptionOF("of.options.EMISSIVE_TEXTURES");
        Option.HELD_ITEM_TOOLTIPS = new IteratableOptionOF("of.options.HELD_ITEM_TOOLTIPS");
        Option.LAZY_CHUNK_LOADING = new IteratableOptionOF("of.options.LAZY_CHUNK_LOADING");
        Option.CUSTOM_SKY = new IteratableOptionOF("of.options.CUSTOM_SKY");
        Option.FAST_MATH = new IteratableOptionOF("of.options.FAST_MATH");
        Option.FAST_RENDER = new IteratableOptionOF("of.options.FAST_RENDER");
        Option.DYNAMIC_FOV = new IteratableOptionOF("of.options.DYNAMIC_FOV");
        Option.DYNAMIC_LIGHTS = new IteratableOptionOF("of.options.DYNAMIC_LIGHTS");
        Option.ALTERNATE_BLOCKS = new IteratableOptionOF("of.options.ALTERNATE_BLOCKS");
        Option.CUSTOM_ENTITY_MODELS = new IteratableOptionOF("of.options.CUSTOM_ENTITY_MODELS");
        Option.ADVANCED_TOOLTIPS = new IteratableOptionOF("of.options.ADVANCED_TOOLTIPS");
        Option.SCREENSHOT_SIZE = new IteratableOptionOF("of.options.SCREENSHOT_SIZE");
        Option.CUSTOM_GUIS = new IteratableOptionOF("of.options.CUSTOM_GUIS");
        Option.RENDER_REGIONS = new IteratableOptionOF("of.options.RENDER_REGIONS");
        Option.SHOW_GL_ERRORS = new IteratableOptionOF("of.options.SHOW_GL_ERRORS");
        Option.SMART_ANIMATIONS = new IteratableOptionOF("of.options.SMART_ANIMATIONS");
        Option.CHAT_BACKGROUND = new IteratableOptionOF("of.options.CHAT_BACKGROUND");
        Option.CHAT_SHADOW = new IteratableOptionOF("of.options.CHAT_SHADOW");
        Option.TELEMETRY = new IteratableOptionOF("of.options.TELEMETRY");
    }
}
