// 
// Decompiled by Procyon v0.5.36
// 

package net.optifine.shaders;

import org.lwjgl.opengl.GL20;

public class ShaderProgramData
{
    public int programIDGL;
    public int uniform_texture;
    public int uniform_lightmap;
    public int uniform_normals;
    public int uniform_specular;
    public int uniform_shadow;
    public int uniform_watershadow;
    public int uniform_shadowtex0;
    public int uniform_shadowtex1;
    public int uniform_depthtex0;
    public int uniform_depthtex1;
    public int uniform_shadowcolor;
    public int uniform_shadowcolor0;
    public int uniform_shadowcolor1;
    public int uniform_noisetex;
    public int uniform_gcolor;
    public int uniform_gdepth;
    public int uniform_gnormal;
    public int uniform_composite;
    public int uniform_gaux1;
    public int uniform_gaux2;
    public int uniform_gaux3;
    public int uniform_gaux4;
    public int uniform_colortex0;
    public int uniform_colortex1;
    public int uniform_colortex2;
    public int uniform_colortex3;
    public int uniform_colortex4;
    public int uniform_colortex5;
    public int uniform_colortex6;
    public int uniform_colortex7;
    public int uniform_gdepthtex;
    public int uniform_depthtex2;
    public int uniform_tex;
    public int uniform_heldItemId;
    public int uniform_heldBlockLightValue;
    public int uniform_fogMode;
    public int uniform_fogColor;
    public int uniform_skyColor;
    public int uniform_worldTime;
    public int uniform_moonPhase;
    public int uniform_frameTimeCounter;
    public int uniform_sunAngle;
    public int uniform_shadowAngle;
    public int uniform_rainStrength;
    public int uniform_aspectRatio;
    public int uniform_viewWidth;
    public int uniform_viewHeight;
    public int uniform_near;
    public int uniform_far;
    public int uniform_sunPosition;
    public int uniform_moonPosition;
    public int uniform_upPosition;
    public int uniform_previousCameraPosition;
    public int uniform_cameraPosition;
    public int uniform_gbufferModelView;
    public int uniform_gbufferModelViewInverse;
    public int uniform_gbufferPreviousProjection;
    public int uniform_gbufferProjection;
    public int uniform_gbufferProjectionInverse;
    public int uniform_gbufferPreviousModelView;
    public int uniform_shadowProjection;
    public int uniform_shadowProjectionInverse;
    public int uniform_shadowModelView;
    public int uniform_shadowModelViewInverse;
    public int uniform_wetness;
    public int uniform_eyeAltitude;
    public int uniform_eyeBrightness;
    public int uniform_eyeBrightnessSmooth;
    public int uniform_terrainTextureSize;
    public int uniform_terrainIconSize;
    public int uniform_isEyeInWater;
    public int uniform_hideGUI;
    public int uniform_centerDepthSmooth;
    public int uniform_atlasSize;
    
    public ShaderProgramData(final int programID) {
        this.programIDGL = programID;
        this.uniform_texture = GL20.glGetUniformLocation(programID, (CharSequence)"texture");
        this.uniform_lightmap = GL20.glGetUniformLocation(programID, (CharSequence)"lightmap");
        this.uniform_normals = GL20.glGetUniformLocation(programID, (CharSequence)"normals");
        this.uniform_specular = GL20.glGetUniformLocation(programID, (CharSequence)"specular");
        this.uniform_shadow = GL20.glGetUniformLocation(programID, (CharSequence)"shadow");
        this.uniform_watershadow = GL20.glGetUniformLocation(programID, (CharSequence)"watershadow");
        this.uniform_shadowtex0 = GL20.glGetUniformLocation(programID, (CharSequence)"shadowtex0");
        this.uniform_shadowtex1 = GL20.glGetUniformLocation(programID, (CharSequence)"shadowtex1");
        this.uniform_depthtex0 = GL20.glGetUniformLocation(programID, (CharSequence)"depthtex0");
        this.uniform_depthtex1 = GL20.glGetUniformLocation(programID, (CharSequence)"depthtex1");
        this.uniform_shadowcolor = GL20.glGetUniformLocation(programID, (CharSequence)"shadowcolor");
        this.uniform_shadowcolor0 = GL20.glGetUniformLocation(programID, (CharSequence)"shadowcolor0");
        this.uniform_shadowcolor1 = GL20.glGetUniformLocation(programID, (CharSequence)"shadowcolor1");
        this.uniform_noisetex = GL20.glGetUniformLocation(programID, (CharSequence)"noisetex");
        this.uniform_gcolor = GL20.glGetUniformLocation(programID, (CharSequence)"gcolor");
        this.uniform_gdepth = GL20.glGetUniformLocation(programID, (CharSequence)"gdepth");
        this.uniform_gnormal = GL20.glGetUniformLocation(programID, (CharSequence)"gnormal");
        this.uniform_composite = GL20.glGetUniformLocation(programID, (CharSequence)"composite");
        this.uniform_gaux1 = GL20.glGetUniformLocation(programID, (CharSequence)"gaux1");
        this.uniform_gaux2 = GL20.glGetUniformLocation(programID, (CharSequence)"gaux2");
        this.uniform_gaux3 = GL20.glGetUniformLocation(programID, (CharSequence)"gaux3");
        this.uniform_gaux4 = GL20.glGetUniformLocation(programID, (CharSequence)"gaux4");
        this.uniform_colortex0 = GL20.glGetUniformLocation(programID, (CharSequence)"colortex0");
        this.uniform_colortex1 = GL20.glGetUniformLocation(programID, (CharSequence)"colortex1");
        this.uniform_colortex2 = GL20.glGetUniformLocation(programID, (CharSequence)"colortex2");
        this.uniform_colortex3 = GL20.glGetUniformLocation(programID, (CharSequence)"colortex3");
        this.uniform_colortex4 = GL20.glGetUniformLocation(programID, (CharSequence)"colortex4");
        this.uniform_colortex5 = GL20.glGetUniformLocation(programID, (CharSequence)"colortex5");
        this.uniform_colortex6 = GL20.glGetUniformLocation(programID, (CharSequence)"colortex6");
        this.uniform_colortex7 = GL20.glGetUniformLocation(programID, (CharSequence)"colortex7");
        this.uniform_gdepthtex = GL20.glGetUniformLocation(programID, (CharSequence)"gdepthtex");
        this.uniform_depthtex2 = GL20.glGetUniformLocation(programID, (CharSequence)"depthtex2");
        this.uniform_tex = GL20.glGetUniformLocation(programID, (CharSequence)"tex");
        this.uniform_heldItemId = GL20.glGetUniformLocation(programID, (CharSequence)"heldItemId");
        this.uniform_heldBlockLightValue = GL20.glGetUniformLocation(programID, (CharSequence)"heldBlockLightValue");
        this.uniform_fogMode = GL20.glGetUniformLocation(programID, (CharSequence)"fogMode");
        this.uniform_fogColor = GL20.glGetUniformLocation(programID, (CharSequence)"fogColor");
        this.uniform_skyColor = GL20.glGetUniformLocation(programID, (CharSequence)"skyColor");
        this.uniform_worldTime = GL20.glGetUniformLocation(programID, (CharSequence)"worldTime");
        this.uniform_moonPhase = GL20.glGetUniformLocation(programID, (CharSequence)"moonPhase");
        this.uniform_frameTimeCounter = GL20.glGetUniformLocation(programID, (CharSequence)"frameTimeCounter");
        this.uniform_sunAngle = GL20.glGetUniformLocation(programID, (CharSequence)"sunAngle");
        this.uniform_shadowAngle = GL20.glGetUniformLocation(programID, (CharSequence)"shadowAngle");
        this.uniform_rainStrength = GL20.glGetUniformLocation(programID, (CharSequence)"rainStrength");
        this.uniform_aspectRatio = GL20.glGetUniformLocation(programID, (CharSequence)"aspectRatio");
        this.uniform_viewWidth = GL20.glGetUniformLocation(programID, (CharSequence)"viewWidth");
        this.uniform_viewHeight = GL20.glGetUniformLocation(programID, (CharSequence)"viewHeight");
        this.uniform_near = GL20.glGetUniformLocation(programID, (CharSequence)"near");
        this.uniform_far = GL20.glGetUniformLocation(programID, (CharSequence)"far");
        this.uniform_sunPosition = GL20.glGetUniformLocation(programID, (CharSequence)"sunPosition");
        this.uniform_moonPosition = GL20.glGetUniformLocation(programID, (CharSequence)"moonPosition");
        this.uniform_upPosition = GL20.glGetUniformLocation(programID, (CharSequence)"upPosition");
        this.uniform_previousCameraPosition = GL20.glGetUniformLocation(programID, (CharSequence)"previousCameraPosition");
        this.uniform_cameraPosition = GL20.glGetUniformLocation(programID, (CharSequence)"cameraPosition");
        this.uniform_gbufferModelView = GL20.glGetUniformLocation(programID, (CharSequence)"gbufferModelView");
        this.uniform_gbufferModelViewInverse = GL20.glGetUniformLocation(programID, (CharSequence)"gbufferModelViewInverse");
        this.uniform_gbufferPreviousProjection = GL20.glGetUniformLocation(programID, (CharSequence)"gbufferPreviousProjection");
        this.uniform_gbufferProjection = GL20.glGetUniformLocation(programID, (CharSequence)"gbufferProjection");
        this.uniform_gbufferProjectionInverse = GL20.glGetUniformLocation(programID, (CharSequence)"gbufferProjectionInverse");
        this.uniform_gbufferPreviousModelView = GL20.glGetUniformLocation(programID, (CharSequence)"gbufferPreviousModelView");
        this.uniform_shadowProjection = GL20.glGetUniformLocation(programID, (CharSequence)"shadowProjection");
        this.uniform_shadowProjectionInverse = GL20.glGetUniformLocation(programID, (CharSequence)"shadowProjectionInverse");
        this.uniform_shadowModelView = GL20.glGetUniformLocation(programID, (CharSequence)"shadowModelView");
        this.uniform_shadowModelViewInverse = GL20.glGetUniformLocation(programID, (CharSequence)"shadowModelViewInverse");
        this.uniform_wetness = GL20.glGetUniformLocation(programID, (CharSequence)"wetness");
        this.uniform_eyeAltitude = GL20.glGetUniformLocation(programID, (CharSequence)"eyeAltitude");
        this.uniform_eyeBrightness = GL20.glGetUniformLocation(programID, (CharSequence)"eyeBrightness");
        this.uniform_eyeBrightnessSmooth = GL20.glGetUniformLocation(programID, (CharSequence)"eyeBrightnessSmooth");
        this.uniform_terrainTextureSize = GL20.glGetUniformLocation(programID, (CharSequence)"terrainTextureSize");
        this.uniform_terrainIconSize = GL20.glGetUniformLocation(programID, (CharSequence)"terrainIconSize");
        this.uniform_isEyeInWater = GL20.glGetUniformLocation(programID, (CharSequence)"isEyeInWater");
        this.uniform_hideGUI = GL20.glGetUniformLocation(programID, (CharSequence)"hideGUI");
        this.uniform_centerDepthSmooth = GL20.glGetUniformLocation(programID, (CharSequence)"centerDepthSmooth");
        this.uniform_atlasSize = GL20.glGetUniformLocation(programID, (CharSequence)"atlasSize");
    }
}
